GET http://localhost:4000/api/participants/all
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOjYwMDExMjIzMywiYWRwYXNzd29yZCI6IjAwMDAiLCJpYXQiOjE2MTQxNTU5MzF9.KZiZZUD9uNIRlkiJWaCsKJQTREVfaWDdhjjSCRptJU8
###

POST http://localhost:4000/api/participants/register
Content-Type: application/json

{
    "fullname" : "test2",
    "age" : 24,
    "email" : "test2@gmail.com",
    "phone" : 614675855,
    "is_valid" : true,
    "online" : true,
    "password" : "azer",
    "score" : 0
}

###

PATCH http://localhost:4000/api/participants/edit/602fadac4d77533ef4d438c7
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOjYwMDExMjIzMywiYWRwYXNzd29yZCI6IjAwMDAiLCJpYXQiOjE2MTM5ODg4NjF9._xSAO9Cu8x6ksCqEM4q8ACe15qtigaZWaRLSXGdmvIQ
Content-Type: application/json

{
    "is_valid" : true,
    "online" : true
}

###
GET http://localhost:4000/api/admins/all
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOjYwMDExMjIzMywiYWRwYXNzd29yZCI6IjAwMDAiLCJpYXQiOjE2MTQxNTU5MzF9.KZiZZUD9uNIRlkiJWaCsKJQTREVfaWDdhjjSCRptJU8


###

POST http://localhost:3001/api/admins/addOne
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOjYwMDExMjIzMywiYWRwYXNzd29yZCI6IjAwMDAiLCJpYXQiOjE2MTQxNTU5MzF9.KZiZZUD9uNIRlkiJWaCsKJQTREVfaWDdhjjSCRptJU8
Content-Type: application/json

{
    "fullname" : "test1",
    "phone" : 1234,
    "password" : "azer"
}


###

POST http://localhost:3001/api/admins/login
Content-Type: application/json

{
    "phone" : 600112233,
    "password" : "0000"
}

###

GET http://localhost:4000/api/questions/getOneQuestion
Authorization: bearer 

###

POST http://localhost:4000/api/questions/add
Authorization: bearer 
Content-Type: application/json

{
    "quest" : "guess my favorite language",
    "answer" : "arabe",
    "points" : 10
}

###

GET http://localhost:4000/api/groups/all
Authorization: bearer 

###


POST http://localhost:4000/api/groups/add
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXJ0aV9uYW1lIjoibmFvdWZhbCIsImlhdCI6MTYxNDIxNjAyM30.jubT2Yu6AeXZVt2LuSikvdchEu2AMusKeVzeLA7GE4Y
Content-Type: application/json

{
    "idparticipant" : "6036e1e4fea2275f4cc6578",
    "groupcode": 888
}


###

POST http://localhost:4000/api/participants/authGroup
Content-Type: application/json

{
    "fullname" : "naoufal"
}

###

POST http://localhost:4000/api/groups/joinGroup
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXJ0aV9uYW1lIjoibmFvdWZhbCIsImlhdCI6MTYxNDIxNjAyM30.jubT2Yu6AeXZVt2LuSikvdchEu2AMusKeVzeLA7GE4Y
Content-Type: application/json

{
    "idparticipant" : "6036e1e4fea2275f04cc6577",
    "groupcode" : 8888 
}

###

GET http://localhost:4000/api/rounds/all

###

POST http://localhost:4000/api/rounds/addRound
Content-Type: application/json

{
    "idgroupmember" : "1111",
    "idquestion" : "6035a10196764b366ce37533",
    "idquestiontoken" : "1234"
}

###
GET http://localhost:4000/api/questionTokens/all

###
POST http://localhost:4000/api/questionTokens/addToken
Content-Type: application/json

{
    "idquestion" : "60315e60bce5524bd0ce71a8",
    "participantanswer" : "24",
    "idparticipant" : "6036e1e4fea2275f04cc6577"
}

###
GET http://localhost:4000/api/winners/all

###
POST http://localhost:4000/api/winners/addWinner
Content-Type: application/json

{
    
}