GET http://localhost:4000/api/participants/all
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOjYwMDExMjIzMywiYWRwYXNzd29yZCI6IjAwMDAiLCJpYXQiOjE2MTM5ODg4NjF9._xSAO9Cu8x6ksCqEM4q8ACe15qtigaZWaRLSXGdmvIQ
###

PATCH http://localhost:4000/api/participants/edit/602fadac4d77533ef4d438c7
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOjYwMDExMjIzMywiYWRwYXNzd29yZCI6IjAwMDAiLCJpYXQiOjE2MTM5ODg4NjF9._xSAO9Cu8x6ksCqEM4q8ACe15qtigaZWaRLSXGdmvIQ
Content-Type: application/json

{
    "is_valid" : true,
    "online" : true
}

###
GET http://localhost:4000/api/admins/all
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOjYwMDExMjIzMywiYWRwYXNzd29yZCI6IjAwMDAiLCJpYXQiOjE2MTM5ODg4NjF9._xSAO9Cu8x6ksCqEM4q8ACe15qtigaZWaRLSXGdmvIQ


###

POST http://localhost:4000/api/admins/addOne
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOjYwMDExMjIzMywiYWRwYXNzd29yZCI6IjAwMDAiLCJpYXQiOjE2MTM5ODg4NjF9._xSAO9Cu8x6ksCqEM4q8ACe15qtigaZWaRLSXGdmvIQ
Content-Type: application/json

{
    "fullname" : "test2",
    "phone" : 123321133,
    "password" : "azer"
}


###

POST http://localhost:4000/api/admins/login
Content-Type: application/json

{
    "phone" : 600112233,
    "password" : "0000"
}

###

# POST http://localhost:4000/api/admins/addOne
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsIjoibmFvdWZhbCIsImlhdCI6MTYxMzczNjMxMX0.-EvV0hIF_JiOagY1mxxn-deSnaAL-kiKhsmb2_7kV3k
# Content-Type: application/json

# {
#     "fullname" : "test1",
#     "phone" : 614675855,
#     "password" : "1234azer"
# }


###

GET http://localhost:4000/api/questions/all
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOjYwMDExMjIzMywiYWRwYXNzd29yZCI6IjAwMDAiLCJpYXQiOjE2MTM5ODg4NjF9._xSAO9Cu8x6ksCqEM4q8ACe15qtigaZWaRLSXGdmvIQ

###

POST http://localhost:4000/api/questions/add
Authorization: bearer 
Content-Type: application/json

{
    "quest" : "guess my favorite language",
    "answer" : "arabe",
    "points" : 10
}

###

GET http://localhost:4000/api/groups/all
Authorization: bearer 

###


POST http://localhost:4000/api/groups/add
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXJ0aV9uYW1lIjoibmFvdWZhbCIsImlhdCI6MTYxMzk4OTMzOH0.UXMJblIF45iVNMRsN42fW0-AlGAed-A5KDiq0rEj9BI
Content-Type: application/json

{
    "idparticipant" : "602fadac4d77533ef4d438c8",
    "groupcode": 9999
}


###

POST http://localhost:4000/api/participants/authGroup
Content-Type: application/json

{
    "fullname" : "naoufal"
}

###

POST http://localhost:4000/api/groups/joinGroup
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXJ0aV9uYW1lIjoibmFvdWZhbCIsImlhdCI6MTYxMzk4OTMzOH0.UXMJblIF45iVNMRsN42fW0-AlGAed-A5KDiq0rEj9BI
Content-Type: application/json

{
    "idparticipant" : "602fadac4d77533ef4d438c9",
    "groupcode": 99
}

###

GET http://localhost:4000/api/rounds/all

###

POST http://localhost:4000/api/rounds/addRound
Content-Type: application/json

{
    "idgroupmember" : "1234",
    "idquestion" : "1234",
    "idquestiontoken" : "1234"
}